import { Category, Series, ProductionDeadline, Holiday, PublicationStatus, Priority } from "./types";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "RT_PUBLICITY", name: "RT Publicity", color: "#FF6B6B", isActive: true },
  { id: "ATIVIDADES_VARIADAS", name: "Atividades Variadas", color: "#4ECDC4", isActive: true },
  { id: "PROGRAMA_BILINGUE", name: "Programa Bilíngue", color: "#9B59B6", isActive: true },
  { id: "EVENTOS_PEDAGOGICOS", name: "Eventos Pedagógicos", color: "#F39C12", isActive: true },
  { id: "FERIADOS", name: "Feriados", color: "#E74C3C", isActive: true },
];

export const DEFAULT_SERIES: Series[] = [
  { id: "MATERNAL", name: "Maternal", order: 1, isActive: true },
  { id: "JARDIM", name: "Jardim", order: 2, isActive: true },
  { id: "PRE", name: "Pré", order: 3, isActive: true },
  { id: "ANO_1", name: "1º Ano", order: 4, isActive: true },
  { id: "ANO_2", name: "2º Ano", order: 5, isActive: true },
  { id: "ANO_3", name: "3º Ano", order: 6, isActive: true },
  { id: "ANO_4", name: "4º Ano", order: 7, isActive: true },
  { id: "ANO_5", name: "5º Ano", order: 8, isActive: true },
  { id: "ANO_6", name: "6º Ano", order: 9, isActive: true },
  { id: "ANO_7", name: "7º Ano", order: 10, isActive: true },
  { id: "ANO_8", name: "8º Ano", order: 11, isActive: true },
  { id: "ANO_9", name: "9º Ano", order: 12, isActive: true },
  { id: "MEDIO_1", name: "1º Médio", order: 13, isActive: true },
  { id: "MEDIO_2", name: "2º Médio", order: 14, isActive: true },
  { id: "MEDIO_3", name: "3º Médio", order: 15, isActive: true },
];

export const DEFAULT_PRODUCTION_DEADLINES: ProductionDeadline[] = [
  // Atividades Variadas
  { id: "av-mat", categoryId: "ATIVIDADES_VARIADAS", seriesId: "MATERNAL", daysBefore: 5, active: true },
  { id: "av-jar", categoryId: "ATIVIDADES_VARIADAS", seriesId: "JARDIM", daysBefore: 7, active: true },
  { id: "av-pre", categoryId: "ATIVIDADES_VARIADAS", seriesId: "PRE", daysBefore: 8, active: true },
  { id: "av-1", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_1", daysBefore: 20, active: true },
  { id: "av-2", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_2", daysBefore: 7, active: true },
  { id: "av-3", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_3", daysBefore: 8, active: true },
  { id: "av-4", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_4", daysBefore: 8, active: true },
  { id: "av-5", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_5", daysBefore: 30, active: true },
  { id: "av-6", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_6", daysBefore: 9, active: true },
  { id: "av-7", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_7", daysBefore: 9, active: true },
  { id: "av-8", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_8", daysBefore: 7, active: true },
  { id: "av-9", categoryId: "ATIVIDADES_VARIADAS", seriesId: "ANO_9", daysBefore: 8, active: true },
  { id: "av-m1", categoryId: "ATIVIDADES_VARIADAS", seriesId: "MEDIO_1", daysBefore: 10, active: true },
  { id: "av-m2", categoryId: "ATIVIDADES_VARIADAS", seriesId: "MEDIO_2", daysBefore: 8, active: true },
  { id: "av-m3", categoryId: "ATIVIDADES_VARIADAS", seriesId: "MEDIO_3", daysBefore: 8, active: true },

  // Programa Bilíngue
  { id: "pb-mat", categoryId: "PROGRAMA_BILINGUE", seriesId: "MATERNAL", daysBefore: 19, active: true },
  { id: "pb-jar", categoryId: "PROGRAMA_BILINGUE", seriesId: "JARDIM", daysBefore: 10, active: true },
  { id: "pb-pre", categoryId: "PROGRAMA_BILINGUE", seriesId: "PRE", daysBefore: 44, active: true },
  { id: "pb-1", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_1", daysBefore: 16, active: true },
  { id: "pb-2", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_2", daysBefore: 17, active: true },
  { id: "pb-3", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_3", daysBefore: 19, active: true },
  { id: "pb-4", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_4", daysBefore: 19, active: true },
  { id: "pb-5", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_5", daysBefore: 11, active: true },
  { id: "pb-6", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_6", daysBefore: 16, active: true },
  { id: "pb-7", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_7", daysBefore: 16, active: true },
  { id: "pb-8", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_8", daysBefore: 14, active: true },
  { id: "pb-9", categoryId: "PROGRAMA_BILINGUE", seriesId: "ANO_9", daysBefore: 19, active: true },
];

export const DEFAULT_STATUSES: { value: PublicationStatus; label: string; color: string; bg: string }[] = [
  { value: "PLANEJAMENTO", label: "Planejamento", color: "text-slate-700", bg: "bg-slate-100" },
  { value: "BRIEFING", label: "Briefing", color: "text-sky-700", bg: "bg-sky-100" },
  { value: "PRODUCAO_CONTEUDO", label: "Produção de Conteúdo", color: "text-amber-700", bg: "bg-amber-100" },
  { value: "DESIGN_ARTE", label: "Design & Arte", color: "text-indigo-700", bg: "bg-indigo-100" },
  { value: "REVISAO_APROVACAO", label: "Revisão / Aprovação", color: "text-purple-700", bg: "bg-purple-100" },
  { value: "AGENDADO", label: "Agendado", color: "text-blue-700", bg: "bg-blue-100" },
  { value: "PUBLICADO", label: "Publicado", color: "text-emerald-700", bg: "bg-emerald-100" },
  { value: "ATRASADO", label: "Atrasado", color: "text-red-700", bg: "bg-red-100" },
  { value: "CANCELADO", label: "Cancelado", color: "text-zinc-600", bg: "bg-zinc-200" },
  { value: "PAUSADO", label: "Pausado", color: "text-yellow-800", bg: "bg-yellow-100" },
  { value: "REPROGRAMADO", label: "Reprogramado", color: "text-orange-700", bg: "bg-orange-100" },
];

export const DEFAULT_PRIORITIES: { value: Priority; label: string; color: string; bg: string }[] = [
  { value: "BAIXA", label: "Baixa", color: "text-slate-600", bg: "bg-slate-100" },
  { value: "MEDIA", label: "Média", color: "text-blue-600", bg: "bg-blue-100" },
  { value: "ALTA", label: "Alta", color: "text-amber-700", bg: "bg-amber-100" },
  { value: "URGENTE", label: "Urgente", color: "text-rose-700", bg: "bg-rose-100 font-bold" },
];

export const DEFAULT_HOLIDAYS_2026: Holiday[] = [
  { id: "h1", name: "Confraternização Universal", date: "2026-01-01", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h2", name: "Carnaval (Segunda-feira)", date: "2026-02-16", year: 2026, type: "FACULTATIVO", recurring: false },
  { id: "h3", name: "Carnaval (Terça-feira)", date: "2026-02-17", year: 2026, type: "FACULTATIVO", recurring: false },
  { id: "h4", name: "Quarta-feira de Cinzas", date: "2026-02-18", year: 2026, type: "FACULTATIVO", recurring: false },
  { id: "h5", name: "Sexta-feira Santa", date: "2026-04-03", year: 2026, type: "NACIONAL", recurring: false },
  { id: "h6", name: "Tiradentes", date: "2026-04-21", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h7", name: "Dia do Trabalho", date: "2026-05-01", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h8", name: "Corpus Christi", date: "2026-06-04", year: 2026, type: "FACULTATIVO", recurring: false },
  { id: "h9", name: "Rev. Constitucionalista (SP)", date: "2026-07-09", year: 2026, type: "ESCOLAR", recurring: true },
  { id: "h10", name: "Independência do Brasil", date: "2026-09-07", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h11", name: "Nossa Senhora Aparecida", date: "2026-10-12", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h12", name: "Dia do Professor", date: "2026-10-15", year: 2026, type: "ESCOLAR", recurring: true },
  { id: "h13", name: "Finados", date: "2026-11-02", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h14", name: "Proclamação da República", date: "2026-11-15", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h15", name: "Dia da Consciência Negra", date: "2026-11-20", year: 2026, type: "NACIONAL", recurring: true },
  { id: "h16", name: "Natal", date: "2026-12-25", year: 2026, type: "NACIONAL", recurring: true },
];

export const INITIAL_SAMPLE_PUBLICATIONS = [
  {
    id: "pub-01",
    title: "Acolhida e Boas-Vindas aos Alunos",
    categoryId: "EVENTOS_PEDAGOGICOS",
    seriesId: "MATERNAL",
    status: "PUBLICADO" as PublicationStatus,
    priority: "ALTA" as Priority,
    publicationDate: "2026-02-02",
    plannedDate: "2026-01-26",
    productionDays: 5,
    responsibleName: "Coordenação Pedagógica",
    description: "Cobertura fotográfica do primeiro dia de aula com os pequenos da Educação Infantil.",
    tags: ["volta-as-aulas", "infantil", "acolhimento"],
  },
  {
    id: "pub-02",
    title: "Projeto Horta & Sustentabilidade",
    categoryId: "ATIVIDADES_VARIADAS",
    seriesId: "ANO_2",
    status: "AGENDADO" as PublicationStatus,
    priority: "MEDIA" as Priority,
    publicationDate: "2026-03-12",
    plannedDate: "2026-03-03",
    productionDays: 7,
    responsibleName: "Prof. Camila",
    description: "Alunos do 2º Ano plantando sementes na horta da escola.",
    tags: ["horta", "ciencias", "pratica"],
  },
  {
    id: "pub-03",
    title: "Storytelling & Puppet Theater",
    categoryId: "PROGRAMA_BILINGUE",
    seriesId: "PRE",
    status: "PRODUCAO_CONTEUDO" as PublicationStatus,
    priority: "ALTA" as Priority,
    publicationDate: "2026-03-20",
    plannedDate: "2026-01-16",
    productionDays: 44,
    responsibleName: "Teacher Jessica",
    description: "Atividade interativa de contação de histórias com fantoches em inglês.",
    tags: ["english", "bilingual", "theatre"],
  },
  {
    id: "pub-04",
    title: "Campanha Matrículas 2026 / Institucional",
    categoryId: "RT_PUBLICITY",
    seriesId: "MEDIO_3",
    status: "DESIGN_ARTE" as PublicationStatus,
    priority: "URGENTE" as Priority,
    publicationDate: "2026-03-25",
    plannedDate: "2026-03-13",
    productionDays: 8,
    responsibleName: "Marketing Central",
    description: "Destaque das aprovações no vestibular e depoimentos dos formandos.",
    tags: ["vestibular", "matriculas", "aprovacoes"],
  },
  {
    id: "pub-05",
    title: "Páscoa Solidária - Arrecadação",
    categoryId: "EVENTOS_PEDAGOGICOS",
    seriesId: "ANO_5",
    status: "PLANEJAMENTO" as PublicationStatus,
    priority: "MEDIA" as Priority,
    publicationDate: "2026-04-01",
    plannedDate: "2026-02-13",
    productionDays: 30,
    responsibleName: "Pastoral Escolar",
    description: "Campanha social de arrecadação de chocolates para instituições de caridade.",
    tags: ["pascoa", "solidariedade"],
  },
];
